apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-draft-demo.fullname" . }}
  labels:
    {{- include "k8s-draft-demo.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "k8s-draft-demo.selectorLabels" . | nindent 6 }}
